language: cpp
compiler: g++
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq cppcheck g++-5 valgrind cmake
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90

script:
  - cd examples/allocator && mkdir build && cp CMakeLists.txt build && cd build && cmake CMakeLists.txt && make
  - valgrind --leak-check=full ./allocatorExample
  - cd ../ && rm -r build && cd ../../
